name: Deploy CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '18.17'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: |
          pushd './'
          pnpm install --frozen-lockfile
          pnpm run build
          popd
        shell: bash

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'linebot-server'
          slot-name: 'Production'
          package: './dist'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  